version: '3.8'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
  api:
    image: node:18.12.1
    volumes:
      - api-data:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    ports:
      - ${API_PORT}:3000
    depends_on:
      - db
  web:
    image: node:18.12.1
    volumes:
      - web-data:/usr/src/app
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - api
volumes:
  api-data:
  web-data:
