version: '3.8'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
  api:
    image: node:18.12.1
    volumes:
      - api-data:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    ports:
      - ${API_PORT}:3000
    depends_on:
      - db
  web:
    image: node:18.12.1
    volumes:
      - web-data:/usr/src/app
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - api
volumes:
  db-data:
  api-data:
  web-data:
