version: '3.8'
name: chirper
services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/entrypoint.sh:/custom-entrypoint.sh
    entrypoint: /custom-entrypoint.sh
  api:
    image: node:18.12.1
    volumes:
      - api-data:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    ports:
      - ${API_PORT}:3000
    depends_on:
      - mysql
  web:
    image: node:18.12.1
    volumes:
      - web-data:/usr/src/app
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - api
volumes:
  api-data:
  web-data:
