version: '3.8'
services:
  db:
    image: mysql:8.0.32
    user: ${UID}:${GID}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./${API_PATH}:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - ${API_PORT}:3000
    depends_on:
      - db
    command: 'ls -lart'
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./${WEB_PATH}:/usr/src/app
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - api
    command: 'npm start'
